version: "3.8"

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: crypto:latest
    environment:
      - PGPORT=5432
      - PGUSR=postgres
      - PGPAS=postgrespw
      - PGHOST=host.docker.internal
      - MGHOST=host.docker.internal
    ports:
      - 8080:8080